apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.name" . | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
type: Opaque
stringData:
  KEY_PRIV_PEM : {{ .Values.server.envVars.yandex.serviceAccount.authKey.privPem | quote }}
